### ISSUE TITLE
Add Nuxt 3 template

### ISSUE THREAD

**Issue by cesarecaoduro** [ThatOpen/engine_templates#5]
@HoyosJuan and @agviegas are you interested in having a template for Nuxt3?
I have managed to create a project that replicates your vanilla template.

![image](https://github.com/ThatOpen/engine_templates/assets/26373891/dfd5a422-c981-4c71-a1bd-aba029c2af7a)

Let me know and I can open a PR.

**Comment by agviegas** [comment]
Hey @cesarecaoduro, thanks a lot for the proposal! The truth is that right now we have some limitations with our small team. 

The bigger our codebase, the slower we get, up to a point that the size of the repos can stop the project in its tracks. So for the templates we will maintain only 1 example that uses our UI-components library, which is compatible with all technologies. 

If we have more resources in the future, we might consider maintaining a collection of libraries. Cheers!
